name: DBT CI/CD

on:
  schedule:
   - cron: '*/5 * * * *' # Runs every 5 minutes 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DBT and Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake
      - name: Set up DBT profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILE }}" > ~/.dbt/profiles.yml
      - name: DBT debug
        run: dbt debug

      - name: DBT test
        run: dbt test

  dbt_cd:
    runs-on: ubuntu-latest
    needs: dbt_ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DBT and Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake
      - name: Set up DBT profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILE }}" > ~/.dbt/profiles.yml
      - name: DBT debug
        run: dbt debug

      - name: DBT run
        run: dbt run